# Generated by Django 5.2.7 on 2025-10-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('contato', models.CharField(max_length=50)),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
