# Generated by Django 5.2.7 on 2025-10-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('licenca', 'Licença')], default='ativo', max_length=10),
        ),
    ]
