# Generated by Django 5.2.7 on 2025-11-02 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0003_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='perfil_usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancer_vinculado', to='freelancers.perfilusuario'),
        ),
    ]
