# Generated by Django 5.2.7 on 2025-10-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor_calculado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
